# Generated by Django 4.2.17 on 2024-12-09 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_article_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_delivery',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
