# Generated by Django 4.2.17 on 2024-12-09 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_article_time_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='time_delivery',
            new_name='time_scheduled',
        ),
    ]
