# Generated by Django 4.2.17 on 2024-12-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_rename_time_delivery_article_time_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
