# Generated by Django 4.2.17 on 2024-12-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_alter_article_time_scheduled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('pib', models.CharField(blank=True, max_length=20, null=True)),
                ('store', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('asked', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cnt_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cnt_total', models.CharField(blank=True, max_length=50, null=True)),
                ('ext', models.CharField(blank=True, max_length=50, null=True)),
                ('cnt', models.CharField(blank=True, max_length=50, null=True)),
                ('signed', models.CharField(blank=True, max_length=100, null=True)),
                ('server_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='coreapp.bill')),
            ],
        ),
    ]
