# Generated by Django 4.2.17 on 2024-12-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_billspec_label_billspec_name_billspec_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billspec',
            name='gtin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
