# Generated by Django 4.2.17 on 2024-12-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_billspec_gtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='time_entry',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='billspec',
            name='time_entry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
